name: SeeWriteSay
description: "see write say Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.6 # 최신 버전 확인
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.2.5
  http: ^1.2.1
  flutter_tts: ^4.2.2
  speech_to_text: ^7.0.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.0
  string_similarity: ^2.0.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.1
  flutter_sound: ^9.2.13
  flutter_native_splash: ^2.4.5
  go_router: ^13.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background:  "#26A69A"  # 앱 배경 색상 (아이콘 배경과 유사한 색)
  adaptive_icon_foreground: "assets/icons/app_icon.png"  # 투명 배경의 아이콘

flutter_native_splash:
  color: "#F9F8F3"
  background_image: "assets/images/splash_logo.png"
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  android_12: # Android 12 이상을 위한 추가 설정
    color: "#F9F8F3" # Android 12 이상 스플래시 화면의 배경색 (흰색)
    image: "assets/images/splash_logo.png" # Android 12 이상 스플래시


flutter:
  assets:
    - assets/images/
    - assets/icons/app_icon.png
    - .env
  uses-material-design: true
