name: see_write_say
description: "see write say Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+6

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  confetti: ^0.8.0
  dio: ^5.8.0+1
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  google_sign_in: ^6.3.0
  provider: ^6.1.4
  flutter_dotenv: ^5.2.1
  url_launcher: ^6.3.1
  http: ^1.3.0
  flutter_tts: ^4.2.2
  speech_to_text: ^7.0.0
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.0
  string_similarity: ^2.1.1
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  flutter_sound: ^9.28.0
  just_audio: ^0.9.46
  flutter_native_splash: ^2.4.6
  go_router: ^14.8.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background:  "#FFFFFF"  # 앱 배경 색상 (아이콘 배경과 유사한 색)
  adaptive_icon_foreground: "assets/icons/app_icon.png"  # 투명 배경의 아이콘

flutter_native_splash:
  color: "#FFFFFF"
  background_image: "assets/images/splash_logo.png"
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  android_12: # Android 12 이상을 위한 추가 설정
    color: "#FFFFFF" # Android 12 이상 스플래시 화면의 배경색 (흰색)
    image: "assets/images/splash_logo.png" # Android 12 이상 스플래시


flutter:
  assets:
    - assets/avatars/
    - assets/images/
    - assets/icons/app_icon.png
    - .env.prod
    - .env.dev
  uses-material-design: true
